#################################### User api list

### Create an user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname": "Hendra",
    "lname": "Wijaya",
    "dob": "2021-10-10",
    "email": "test@yahoo.com",
    "password": "aaaaaaa",
    "phone": "012345678",
    "address": "Sydney",
    "gender":"Male"
}

### Email verification api 
POST http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "otp": "29336820",
    "email" : "test@yahoo.com"
}

### User login
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email" : "hendra.here@yahoo.com", 
    "password" : "123456"
}

#################################### Category api list

### Create new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
 "name" : "Electric Vehicle ",
 "parentCat" : null
}

### Fetch all category/s 
GET http://localhost:8000/api/v1/category


### Delete category
Delete http://localhost:8000/api/v1/category


### Update category
PATCH  http://localhost:8000/api/v1/category
Content-Type: application/json

{
 "_id": "61525b4412ec817bb1a6cb44",
 "name" : "Electric Vehicle 2 ",
 "parentCat" : ""
}

###Delete category 
DELETE http://localhost:8000/api/v1/category/fdasgrwg436346rsg

#################################### Token api 

GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbmRyYS5oZXJlQHlhaG9vLmNvbSIsImlhdCI6MTYzMzM4NDEzOCwiZXhwIjoxNjM1OTc2MTM4fQ.mTLLPnC9BCbv6RtmIT40n8caF87gBUqreJ60jfdkkKs