#################################### User api list

### Create an user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname": "Hendra",
    "lname": "Wijaya",
    "dob": "2021-10-10",
    "email": "test@yahoo.com",
    "password": "aaaaaaa",
    "phone": "012345678",
    "address": "Sydney",
    "gender":"Male"
}

### Email verification api 
POST http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "otp": "29336820",
    "email" : "test@yahoo.com"
}

#################################### Category api list

### Create new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
 "name" : "Electric Vehicle ",
 "parentCat" : null
}

### Fetch all category/s 
GET http://localhost:8000/api/v1/category


### Delete category
Delete http://localhost:8000/api/v1/category



### Update category